from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import matplotlib
if "matplotlib.pyplot" not in sys.modules:
    matplotlib.use("Agg")
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt

from metrics_plots import (
    plot_loss_curves,
    plot_optimization_dynamics,
    plot_qnn_output_variance,
    plot_theta_heatmap,
    plot_sensitivity_score,
)


def load_metrics_npz(path: Path) -> Tuple[Dict[str, object], Dict[str, object]]:
    with np.load(path, allow_pickle=True) as data:
        metrics = {k: data[k] for k in data.files}
    meta = {}
    raw = metrics.pop("meta", None)
    if raw is not None:
        try:
            meta = json.loads(str(raw[0]))
        except (ValueError, TypeError):
            meta = {}
    return metrics, meta


def _meta_lines(meta: Dict[str, object]) -> list[str]:
    if not meta:
        return []

    lines = []
    run_tag = meta.get("run_tag")
    timestamp = meta.get("timestamp")
    if run_tag:
        lines.append(f"Run tag: {run_tag}")
    if timestamp:
        lines.append(f"Timestamp: {timestamp}")

    mode = meta.get("mode")
    feature_mode = meta.get("feature_mode")
    circuit_type = meta.get("circuit_type")
    entanglement = meta.get("entanglement")
    use_dense_head = meta.get("use_dense_head")
    if any(x is not None for x in [mode, feature_mode, circuit_type, entanglement, use_dense_head]):
        lines.append(
            "Mode: {mode} | Feature: {feature} | Circuit: {circuit} | Entanglement: {ent} | Dense head: {head}".format(
                mode=mode if mode is not None else "n/a",
                feature=feature_mode if feature_mode is not None else "n/a",
                circuit=circuit_type if circuit_type is not None else "n/a",
                ent=entanglement if entanglement is not None else "n/a",
                head=bool(use_dense_head) if use_dense_head is not None else "n/a",
            )
        )

    n_qubits = meta.get("n_qubits")
    n_layers = meta.get("n_layers")
    batch_size = meta.get("batch_size")
    lr = meta.get("learning_rate")
    n_epochs = meta.get("n_epochs")
    if any(x is not None for x in [n_qubits, n_layers, batch_size, lr, n_epochs]):
        lines.append(
            "Qubits: {q} | Layers: {l} | Batch: {b} | LR: {lr} | Epochs: {e}".format(
                q=n_qubits if n_qubits is not None else "n/a",
                l=n_layers if n_layers is not None else "n/a",
                b=batch_size if batch_size is not None else "n/a",
                lr=lr if lr is not None else "n/a",
                e=n_epochs if n_epochs is not None else "n/a",
            )
        )

    return lines


def _cover_page(title: str, source_path: Path, meta: Dict[str, object]) -> plt.Figure:
    fig = plt.figure(figsize=(8.27, 11.69))
    fig.text(0.5, 0.82, title, ha="center", va="center", fontsize=16)
    fig.text(0.5, 0.78, "Temporary debug report", ha="center", va="center", fontsize=10)
    fig.text(0.5, 0.74, f"Source: {source_path}", ha="center", va="center", fontsize=9)
    fig.text(0.5, 0.70, "Generated by metrics_report.py", ha="center", va="center", fontsize=9)
    meta_lines = _meta_lines(meta)
    y = 0.64
    for line in meta_lines:
        fig.text(0.5, y, line, ha="center", va="center", fontsize=9)
        y -= 0.03
    return fig


def _add_footer(fig: plt.Figure, source_path: Path) -> None:
    fig.text(0.5, 0.01, f"Source: {source_path}", ha="center", va="bottom", fontsize=8, alpha=0.7)


def _last_finite(values: object) -> float:
    arr = np.asarray(values)
    if arr.size == 0:
        return float("nan")
    mask = np.isfinite(arr)
    if not np.any(mask):
        return float("nan")
    return float(arr[mask][-1])


def _summary_page(metrics: Dict[str, object], source_path: Path, meta: Dict[str, object]) -> plt.Figure:
    fig = plt.figure(figsize=(8.27, 11.69))
    fig.text(0.5, 0.93, "Key Metrics Summary (Last Epoch)", ha="center", va="center", fontsize=14)

    epochs = len(metrics.get("train_loss_per_epoch", []))
    theta = np.asarray(metrics.get("theta_trajectory", []))
    theta_params = int(theta.shape[1]) if theta.ndim == 2 else 0

    sections = [
        ("RUN", [
            f"Source metrics: {source_path}",
            f"Run tag: {meta.get('run_tag', 'n/a')}",
            f"Timestamp: {meta.get('timestamp', 'n/a')}",
            f"Mode: {meta.get('mode', 'n/a')}",
            f"Feature mode: {meta.get('feature_mode', 'n/a')}",
            f"Circuit type: {meta.get('circuit_type', 'n/a')}",
            f"Entanglement: {meta.get('entanglement', 'n/a')}",
            f"Dense head: {meta.get('use_dense_head', 'n/a')}",
            f"Qubits: {meta.get('n_qubits', 'n/a')}",
            f"Layers: {meta.get('n_layers', 'n/a')}",
            f"Batch size: {meta.get('batch_size', 'n/a')}",
            f"Learning rate: {meta.get('learning_rate', 'n/a')}",
            f"Configured epochs: {meta.get('n_epochs', 'n/a')}",
            f"Observed epochs: {epochs}",
            f"Theta params: {theta_params if theta_params else 'n/a'}",
        ]),
        ("LOSS (MSE)", [
            f"Train: {_last_finite(metrics.get('train_loss_per_epoch', [])):.6e}",
            f"Validation: {_last_finite(metrics.get('val_loss_per_epoch', [])):.6e}",
        ]),
        ("GRADIENT NORMS (L2)", [
            f"Quantum: {_last_finite(metrics.get('quantum_grad_norm_per_epoch', [])):.6e}",
            f"Classical (head): {_last_finite(metrics.get('classical_grad_norm_per_epoch', [])):.6e}",
        ]),
        ("UPDATE NORMS (L2)", [
            f"Quantum: {_last_finite(metrics.get('quantum_update_norm_per_epoch', [])):.6e}",
            f"Classical (head): {_last_finite(metrics.get('classical_update_norm_per_epoch', [])):.6e}",
            f"Update ratio (d_theta / d_phi): {_last_finite(metrics.get('update_balance_ratio_per_epoch', [])):.6f}",
        ]),
        ("QNN OUTPUT (RAW, BEFORE HEAD)", [
            f"Mean: {_last_finite(metrics.get('qnn_output_mean_per_epoch', [])):.6f}",
            f"Variance: {_last_finite(metrics.get('qnn_output_var_per_epoch', [])):.6f}",
            f"Min: {_last_finite(metrics.get('qnn_output_min_per_epoch', [])):.6f}",
            f"Max: {_last_finite(metrics.get('qnn_output_max_per_epoch', [])):.6f}",
        ]),
        ("PREDICTION SMOOTHNESS", [
            f"Mean L2 diff: {_last_finite(metrics.get('sensitivity_scores', [])):.6e}",
        ]),
    ]

    x_positions = [0.08, 0.55]
    col_idx = 0
    y = 0.88
    y_bottom = 0.08
    header_step = 0.024
    item_step = 0.020
    section_gap = 0.012

    for header, lines in sections:
        needed_height = header_step + len(lines) * item_step + section_gap
        if y - needed_height < y_bottom and col_idx == 0:
            col_idx = 1
            y = 0.88

        x = x_positions[col_idx]
        fig.text(x, y, header, ha="left", va="top", fontsize=10, fontweight="bold")
        y -= header_step
        for line in lines:
            fig.text(x + 0.02, y, line, ha="left", va="top", fontsize=9)
            y -= item_step
        y -= section_gap

    return fig


def generate_pdf_report(metrics: Dict[str, object], meta: Dict[str, object], output_path: Path, source_path: Path) -> None:
    figures = [
        _cover_page("QNN Metrics Report (Temporary Debug)", source_path, meta),
        _summary_page(metrics, source_path, meta),
        plot_loss_curves(metrics),
        plot_optimization_dynamics(metrics),
        plot_qnn_output_variance(metrics),
        plot_theta_heatmap(metrics),
        plot_sensitivity_score(metrics),
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with PdfPages(output_path) as pdf:
        for fig in figures:
            if fig is None:
                continue
            _add_footer(fig, source_path)
            pdf.savefig(fig)
            plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a debug PDF report from QNN metrics.")
    parser.add_argument(
        "--metrics",
        type=Path,
        default=Path("qnn/results/metrics/latest/_tmp_metrics_latest_debug.npz"),
        help="Path to the temporary debug metrics .npz file.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("qnn/results/reports/latest/_tmp_metrics_latest_debug.pdf"),
        help="Output PDF path.",
    )
    args = parser.parse_args()

    if not args.metrics.exists():
        raise SystemExit(f"Metrics file not found: {args.metrics}")

    metrics, meta = load_metrics_npz(args.metrics)
    generate_pdf_report(metrics, meta, args.out, args.metrics)
    print(f"Wrote debug report to {args.out}")


if __name__ == "__main__":
    main()
